---
title: "Getting started"
teaching: 10
exercises: 2
---

::::::::::::::::::::::::::::::::::::: questions 

- Programming - why bother?
- Why python?
- How to learn?

::::::::::::::::::::::::::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::: objectives

- Understand the concept of programming
- Understand the basics of Python language
::::::::::::::::::::::::::::::::::::::::::::::::

## Programming --- why bother?
<p style='text-align: justify;'> 
Data handling and analysis in bio-research and medicine is best done using coding. In October 2017,  the American technology magazine Wired published an [article](https://www.wired.com/2017/03/biologists-teaching-code-survive/) in which the author outlines reasons why several established bio-science researchers working in reputable institutions felt the need to learn coding --- specifically in Python: "Want to Make It as a Biologist? Better Learn to Code".
</p>

::::::::::::::::::::::::::::::::::::: callout	

## This Course
<p style='text-align: justify;'>
Focusing on the Python programming language throughout this course, we will discuss some universal principles shared amongst many programming languages. Through a diverse range of examples, we will be training these principles by solving problems that we face in biological and medical research.
</p>

::::::::::::::::::::::::::::::::::::::::::::::


## Why Python?
<p style='text-align: justify;'>
Python is a general-purpose programming language. This means that it can be exploited to design any type of software, from desktop and web, to robotics and automation, to data analysis. The 2020 survey conducted by the Python Software Foundation and JetBrains^&#174;^ found that approximately 85% of respondents used Python  as their first language [to conduct data analysis](https://www.jetbrains.com/research/python-developers-survey-2017/#types-of-development).
</p>

<p style='text-align: justify;'>
In addition, the 2021 developer survey conducted by StackOverflow found that Python is the [third most popular](https://insights.stackoverflow.com/survey/2021#most-popular-technologies-language) general-purpose programming language after JavaScript and HTML/CSS. This means that it enjoys a vibrant community that support and maintain its development, and the development of the libraries associated with it. This is confirmed by the fact that the language is ranked as the [second most popular language on GitHub^&#174;^](https://madnight.github.io/githut/#/pull_requests/2018/1), which is the primary code-sharing platform amongst programmers.
</p>

:::::::::::::::::::::::::::::::::::::::::::::::: discussion

## How to learn?	
<p style='text-align: justify;'>
Learning how to code as a beginner is akin to learning how to walk as a baby. You cannot learn programming by memorising directives; no matter how well you memorise them. To learn how to code, one must learn how think algorithmically; that is, how to break different tasks down into logical procedures. The only way to learn how to think that way is to practice, make mistakes, and how to overcome those mistakes. It is common to make the same mistake more than once, especially in different contexts, and that can become frustrating at times. However, once you get it, you will have it for life.
</p>

<p style='text-align: justify;'>	
There are lots materials on the web, both free and paid, to assist with your learning. Use them to your advantage! Great programmers are not the ones who know every technical detail by heart; rather, they are the ones who know what they are looking for, and where they can find the answer.	
</p>

:::::::::::::::::::::::::::::::::::::::::::::::: 

::::::::::::::::::::::::::::::::::::: callout
## Known Quirk
<p style='text-align: justify;'>
Unlike popular belief, the name **Python** has nothing to do with the snake. It is in fact derived from the popular British sketch comedy series [Monty Python's Flying Circus](https://en.wikipedia.org/wiki/Monty_Python\%27s_Flying_Circus), of which van Rossum was a self-confessed fan.
</p>

::::::::::::::::::::::::::::::::::::::::::::::: 

## Python: The Programming Language
<p style='text-align: justify;'>
Python is a general-purpose, high-level programming language. It was invented by the Dutch computer programmer [Guido van Rossum](https://en.wikipedia.org/wiki/Guido_van_Rossum) and was released for the first time in 1990. 
</p>
<p style='text-align: justify;'>	
A **high-level** programming language is a language that enjoys strong abstraction from computer details. This means that it is closer to the language that is spoken and understood by humans; which put simply, makes the language more enjoyable to work with.
</p>	

:::::::::::::::::::::::::::::::::::::::::::::::: discussion	
## Categories
<p style='text-align: justify;'>
In terms of compilation, programming languages may be divided into two different categories:
</p>

<p style='text-align: justify;'>
1 - **Compiled ** These are languages whose code is translated (compiled) into machine language en-masse, and in advance, using a designated compiler programme --- e.g.\  C, Rust, Haskell.
</p>
<p style='text-align: justify;'>
2- **Interpreted** Rely on and must *always* be accompanied with an interpreter, whose job is to translate the source code into machine language one line at a time --- e.g.\  Python, R, MATLAB^&#174;^.
</p>

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: 




::::::::::::::::::::::::::::::::::::: keypoints 

- Programming is an important skill which is highly applicable to bio-research and medicine.
- Python is one of the most popular programming language for being general-purpose and high level language.
- Python requires interpreter for line by line code translation. 

::::::::::::::::::::::::::::::::::::::::::::::::

[r-markdown]: https://rmarkdown.rstudio.com/
